# This compose file is useful for testing https.
# The .env file sets ENVVARS for the Docker CLI used by this compose file.
---
version: "3.8"
services:
  cms:
    image: taccwma/core-cms:latest
    volumes:
      - ./conf/cms/secrets.py:/code/taccsite_cms/secrets.py
      - ./conf/cms/settings.py:/code/taccsite_cms/settings.py
      - ./conf/cms/settings_overrides.py:/code/taccsite_cms/settings_overrides.py
      - ./conf/cms/urls.py:/code/taccsite_cms/urls.py
      - ./conf/cms/urls_overrides.py:/code/taccsite_cms/urls_overrides.py
      - ./apps:/code/apps
      - ../../cms/static:/code/static
      - ../../cms/media:/code/media
    command: python manage.py runserver 0.0.0.0:8000
    container_name: core_portal_cms
    ports:
      - 8000:8000
    depends_on:
      - postgrescms

  memcached:
    image: memcached:latest
    container_name: core_portal_memcached


  postgrescms:
    image: postgres:11.5
    volumes:
      - core_cms_postgres_data:/var/lib/postgresql/data/portal
    container_name: core_cms_postgres
    environment:
      - POSTGRES_PASSWORD=taccforever
      - POSTGRES_USER=postgresadmin
      - POSTGRES_DB=taccsite
      - PGDATA=/var/lib/postgresql/data/portal



volumes:
  core_cms_postgres_data:
